### ISSUE TITLE
ERROR_CAPTCHA_UNSOLVABLE

### ISSUE THREAD

**Issue by alikeremo** [V4NSH4J/discord-mass-DM-GO#505]
![Ekran Görüntüsü (43)](https://user-images.githubusercontent.com/88512101/163171444-028f0f22-6b86-4864-90fe-bbdccea69898.png)

Hi guys hope you are doing well, I've been getting this error continuously do you have and idea how can ı solve that?

**Comment by alikeremo** [comment]
```
direct_message_settings:
  individual_delay: 60
  rate_limit_delay: 60
  offset: 300
  max_dms_per_token: 0
  skip_completed: true
  call: false
  remove_dead_tokens: true 
  remove_completed_members: true 
  stop_dead_tokens: true 
  check_mutual: false
  friend_before_DM: false
  online_tokens: false
  receive_messages: false
  skip_failed: false
  block_after_dm: false
  close_dm_after_message: false

proxy_settings:
  proxy_from_file: true
  proxy_for_captcha: true 
  use_proxy_for_gateway: false
  proxy_protocol: "http"
  timeout: 120

scraper_settings:
  online_scraper_delay: 3000
  scrape_usernames: false
  scrape_avatars: false

captcha_settings:
  captcha_api_key: "**************************"
  captcha_api: "2captcha.com"
  max_captcha_wait: 120
  max_captcha_retry: 2

other_settings: 
  disable_keep_alives: false

suspicion_avoidance:
  random_individual_delay: 20
  random_rate_limit_delay: 20
  random_delay_before_dm: 20
```

This is the config I use any ideas?
