### ISSUE TITLE
anti captcha not working for mass dm 

### ISSUE THREAD

**Issue by dcryptodev** [V4NSH4J/discord-mass-DM-GO#564]
I tried with **capmonster.cloud** and also tried with **anti-captcha.com** and its not working at all 

```
Enter your choice: 
2
Mass DM Advertiser/Spammer
This will DM everyone in memberids.txt from your tokens
Press 1 to use messages from file or press 2 to enter a message: 
1
[18:24:41] Do you wish to use Advanced Settings? 0: No, 1: Yes: 
0
[18:24:54] Captcha detected TOKEN-ID Solving
[18:25:24] Token TOKEN-ID Captcha was solved incorrectly
```

This is my config. yml
```

direct_message_settings:
  individual_delay: 60
  rate_limit_delay: 60
  offset: 100
  max_dms_per_token: 0
  skip_completed: true
  call: false
  remove_dead_tokens: true 
  remove_completed_members: true 
  stop_dead_tokens: true 
  check_mutual: false
  friend_before_DM: false
  online_tokens: false
  receive_messages: false
  skip_failed: false
  block_after_dm: false
  close_dm_after_message: false

proxy_settings:
  proxy_from_file: false
  proxy_for_captcha: false
  use_proxy_for_gateway: false
  proxy_protocol: "http"
  timeout: 60

scraper_settings:
  online_scraper_delay: 3000
  scrape_usernames: false
  scrape_avatars: false

captcha_settings:
  captcha_api_key: "MY-KEY"
  captcha_api: "capmonster.cloud"
  max_captcha_wait: 120
  max_captcha_retry_dm: 0
  max_captcha_retry_invite: 3
  
  other_settings: 
  disable_keep_alives: false

suspicion_avoidance:
  random_individual_delay: 0
  random_rate_limit_delay: 0
  random_delay_before_dm: 0
  typing: false
  typing_variation: 250
  typing_speed: 450
  typing_base: 200

dm_on_react:
  observer_token: ""
  change_name: true
  change_avatar: true 
  invite: ""
  server_id: ""
  channel_id: ""
  message_id: ""
  emoji: ""
  skip_completed: true 
  skip_failed: true 
  leave_token_on_ratelimit: true 
  rotate_tokens: true
  max_anti_raid_queue: 20
  max_dms_per_token: 10

```
Would appreciate your help @V4NSH4J
